server:
  port: 7271

spring:
  kafka:
    bootstrap-servers: 192.168.235.102:9092
   #bootstrap-servers=192.168.235.102:9093,192.168.235.102:9094,192.168.235.102:9095

    # producer
    producer:
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432
      acks: all
      properties:
        linger:
          ms: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    # consumer
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
